services:
  - type: web
    name: puxxzatj-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: INWCLOUD_API_KEY
        sync: false
      - key: ADMIN_IDS
        sync: false
    disk:
      name: puxxza-db
      mountPath: /data
      sizeGB: 1
